### ISSUE TITLE
Support 10.9 only ?

### ISSUE THREAD

**Issue by thelinuxfr** [Darkomen78/Fusioninventory#1]
Bonjour,

Bravo pour le travail :+1: Une seule petite chose chez moi, c'est que les paquets ne fonctionnent que sur 10.9 :) .

Avez-vous de quoi compiler sur les systèmes plus anciens ?

Merci d'avance
Cordialement

**Comment by Darkomen78** [comment]
Ajout du support pour les 10.8 et 10.10 dans le nouveau script de build. Il me faut un expert perl et/ou fusioninventory pour comprendre pourquoi les autre système ne fonctionne pas.
