### ISSUE TITLE
Modal dialog prevents silent install

### ISSUE THREAD

**Issue by ftrojahn** [Darkomen78/Fusioninventory#4]
Hello,

having downloaded your zip from
https://github.com/Darkomen78/Fusioninventory/blob/master/build/FusionInventory2.3.10.1.zip
as adviced on http://www.fusioninventory.org, it is not possible to deploy the mpkg using e.g. munki.

How can I suppress the modal dialogue, asking for Tag, Server, Local folder?

Even the "deploy" package hangs and asks ... (on 10.10 yosemite)
https://github.com/Darkomen78/Fusioninventory/blob/master/build/FusionInventory_deploy2.3.10.1.zip

Any advice?

Thanx in advance

**Comment by Darkomen78** [comment]
You can use the new "deploy" package to avoid this dialog. Use the Build script to get it.
